version: '2'

services:

  web:
      hostname: 'web-php'
      image: webdevops/php-apache:ubuntu-16.04
      ports:
        - "4000:80"
      volumes:
        - ./php:/app
      links:
        - database:database
      working_dir: /app
      restart: always


  database:
    hostname: 'boris-db'
    image: mysql:latest
    volumes:
      - ./.model:/var/lib/mysql
      - ./dump/back:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=123
    ports:
       - "10000:3306"
